# 服务器相关
server:
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
  port: 8989
# 数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cmfz
# 视图解析器
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
# mybatis
mybatis:
  type-aliases-package: com.baizhi.lzz.entity
  mapper-locations: classpath:com/baizhi/mapper/*.xml
logging:
  level:
    com.baizhi.dao: debug